# Generated by Django 5.1.5 on 2025-02-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_state', models.JSONField()),
                ('current_turn', models.CharField(default='white', max_length=10)),
                ('mode', models.CharField(choices=[('official', 'Official'), ('custom', 'Custom')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ChessPieceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_name', models.CharField(max_length=50, unique=True)),
                ('movement_rules', models.JSONField()),
            ],
        ),
    ]
